Create script.txt
ChiragBellara/Video-Translation-Using-Deep-Learning pull request #8
Opened 2023-10-23 03:07 UTC by silbunsa

Initial folder structure will upload the code shortly for review.

2023-10-23 03:23 UTC, zeshengchen requested changes
Please explain what is content in "TTS_with_bark/script.txt" and why upload this file!

Moreover, it is preferable to include all necessary code as ONE pull request. Such a pull request is NOT really a pull request!

2023-10-23 03:57 UTC, silbunsa commented
I created the folder structure for the code. Script.txt is an example text file for translation.

2023-10-23 14:06 UTC, zeshengchen requested changes
Should file "TextToSpeech.ipynb" be under root? If so, why?

2023-10-23 14:09 UTC, zeshengchen requested changes
For "TTS_bark_mainipynb.ipynb", for the last line of the code, which is commented out. If it is no longer useful, please simply remove it!

2023-10-23 14:24 UTC, silbunsa commented
> Should file "TextToSpeech.ipynb" be under root? If so, why?
It was a mistake, it shouldn't be there, I am removing the file.

2023-10-23 14:26 UTC, silbunsa commented
> For "TTS_bark_mainipynb.ipynb", for the last line of the code, which is commented out. If it is no longer useful, please simply remove it!

I was confused of how the tts.wav file should be used, saved or sent directly. I am commenting out the last line as to save it as for now.

2023-10-23 15:50 UTC, zeshengchen approved these changes

2023-10-23 21:10 UTC, roh-it approved these changes

2023-10-24 01:46 UTC, SaiSurajMatta approved these changes

2023-10-24 17:04 UTC, ChiragBellara requested changes

2023-10-24 17:04 UTC, ChiragBellara commented on TTS_with_bark/TTS_bark_mainipynb.ipynb
Can you add what each of these parameters implies and what are the possible values for them?
semantic_tokens = generate_text_semantic(
        sentence,
        history_prompt=SPEAKER,
        temp=GEN_TEMP,
        min_eos_p=0.05,  # this controls how likely the generation is to end
    )

Also, is it possible to make this whole thing a function that takes the name of a text file as input and returns the name and location of the audio file ?
script_file = "script.txt"
with open(script_file, "r") as file:
  script = file.read()
script.replace("\n", " ").strip()


sentences = nltk.sent_tokenize(script)
SPEAKER = "v2/hi_speaker_6"
silence = np.zeros(int(0.25 * SAMPLE_RATE))  # quarter second of silence

GEN_TEMP = 0.6
SPEAKER = "v2/hi_speaker_3"
silence = np.zeros(int(0.25 * SAMPLE_RATE))  # quarter second of silence

pieces = []
for sentence in sentences:
    semantic_tokens = generate_text_semantic(
        sentence,
        history_prompt=SPEAKER,
        temp=GEN_TEMP,
        min_eos_p=0.05,  # this controls how likely the generation is to end
    )

    audio_array = semantic_to_waveform(semantic_tokens, history_prompt=SPEAKER,)
    pieces += [audio_array, silence.copy()]

Audio(np.concatenate(pieces), rate=SAMPLE_RATE)
scipy.io.wavfile.write("text_speech.wav", rate=SAMPLE_RATE, data=audio_array)

Note: I am unable to comment on the file directly as the file is too big to load on the website.

2023-10-25 04:53 UTC, silbunsa commented on TTS_with_bark/TTS_bark_mainipynb.ipynb
Changed it as you suggested, Check it!

2023-10-25 16:28 UTC, ChiragBellara approved these changes
Thanks. This is good to merge.

2023-10-25 16:28 UTC, merged